---

- name: "webserver package installation"
  yum:
    name: "{{ webserver_packages }}"
    state: present

- name: "Creating configuration files from template"
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    
- name: "Creating virtual host from template"
  template:
    src: virtualhost.conf.j2
    dest: /etc/httpd/conf.d/default.conf
    
- name: "Creating documentroot for {{ httpd_servername }}"
  file:
    path: "{{ httpd_docroot }}"
    state: directory
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
    
- name: "Creating phpinfo page"
  copy:
    src: test.php
    dest: "{{ httpd_docroot }}"
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}" 
    
- name: "restarting services httpd &php"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
    - httpd
    - php-fpm

- name: "mariadb-server package installation"
  yum:
    name: mariadb105-server, python3-pip
    state: present
    
- name: "mariadb-server restart service"
  service:
    name: mariadb
    state: restarted
    enabled: true
    
- name: "mariadb server -install php mysql extension"
  pip:
    name: "pymysql"
    state: present
    
- name: "mariadb-server - setting root password"
  ignore_errors: true
  community.mysql.mysql_user:
    login_user: "root"
    login_password: ""
    login_unix_socket: /var/lib/mysql/mysql.sock
    user: "root"
    password: "{{ mariadb_root_password }}"
    
- name: "mariadb-server removing anonymous users"
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    user: ""
    state: absent
    
- name: "mariadb -server removing test database"
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "test"
    state: absent
    
- name: "mariadb -server creating database {{ mariadb_extra_db }}"
  community.mysql.mysql_db:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ mariadb_extra_db }}"
    state: present
    
- name: "mariadb -server creating database {{ mariadb_extra_user }}"
  community.mysql.mysql_user:
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: "{{ mariadb_extra_user }}"
    password: "{{ mariadb_extra_password }}"
    state: present
    priv:  "{{ mariadb_extra_db }}.*:ALL"
